// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Diagnose is the predicate function for diagnose builders.
type Diagnose func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Illness is the predicate function for illness builders.
type Illness func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Symptoms is the predicate function for symptoms builders.
type Symptoms func(*sql.Selector)
