// Code generated by entc, DO NOT EDIT.

package illness

import (
	"github.com/ADMIN/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// IllnessName applies equality check predicate on the "Illness_Name" field. It's identical to IllnessNameEQ.
func IllnessName(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIllnessName), v))
	})
}

// IllnessNameEQ applies the EQ predicate on the "Illness_Name" field.
func IllnessNameEQ(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldIllnessName), v))
	})
}

// IllnessNameNEQ applies the NEQ predicate on the "Illness_Name" field.
func IllnessNameNEQ(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldIllnessName), v))
	})
}

// IllnessNameIn applies the In predicate on the "Illness_Name" field.
func IllnessNameIn(vs ...string) predicate.Illness {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Illness(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldIllnessName), v...))
	})
}

// IllnessNameNotIn applies the NotIn predicate on the "Illness_Name" field.
func IllnessNameNotIn(vs ...string) predicate.Illness {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Illness(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldIllnessName), v...))
	})
}

// IllnessNameGT applies the GT predicate on the "Illness_Name" field.
func IllnessNameGT(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldIllnessName), v))
	})
}

// IllnessNameGTE applies the GTE predicate on the "Illness_Name" field.
func IllnessNameGTE(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldIllnessName), v))
	})
}

// IllnessNameLT applies the LT predicate on the "Illness_Name" field.
func IllnessNameLT(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldIllnessName), v))
	})
}

// IllnessNameLTE applies the LTE predicate on the "Illness_Name" field.
func IllnessNameLTE(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldIllnessName), v))
	})
}

// IllnessNameContains applies the Contains predicate on the "Illness_Name" field.
func IllnessNameContains(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldIllnessName), v))
	})
}

// IllnessNameHasPrefix applies the HasPrefix predicate on the "Illness_Name" field.
func IllnessNameHasPrefix(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldIllnessName), v))
	})
}

// IllnessNameHasSuffix applies the HasSuffix predicate on the "Illness_Name" field.
func IllnessNameHasSuffix(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldIllnessName), v))
	})
}

// IllnessNameEqualFold applies the EqualFold predicate on the "Illness_Name" field.
func IllnessNameEqualFold(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldIllnessName), v))
	})
}

// IllnessNameContainsFold applies the ContainsFold predicate on the "Illness_Name" field.
func IllnessNameContainsFold(v string) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldIllnessName), v))
	})
}

// HasIllnessDiagnose applies the HasEdge predicate on the "illness_diagnose" edge.
func HasIllnessDiagnose() predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IllnessDiagnoseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IllnessDiagnoseTable, IllnessDiagnoseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIllnessDiagnoseWith applies the HasEdge predicate on the "illness_diagnose" edge with a given conditions (other predicates).
func HasIllnessDiagnoseWith(preds ...predicate.Diagnose) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(IllnessDiagnoseInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, IllnessDiagnoseTable, IllnessDiagnoseColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Illness) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Illness) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Illness) predicate.Illness {
	return predicate.Illness(func(s *sql.Selector) {
		p(s.Not())
	})
}
