// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"

	// EdgePatientDiagnose holds the string denoting the patient_diagnose edge name in mutations.
	EdgePatientDiagnose = "patient_diagnose"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// PatientDiagnoseTable is the table the holds the patient_diagnose relation/edge.
	PatientDiagnoseTable = "diagnoses"
	// PatientDiagnoseInverseTable is the table name for the Diagnose entity.
	// It exists in this package in order to avoid circular dependency with the "diagnose" package.
	PatientDiagnoseInverseTable = "diagnoses"
	// PatientDiagnoseColumn is the table column denoting the patient_diagnose relation/edge.
	PatientDiagnoseColumn = "patient_patient_diagnose"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
}

var (
	// PatientNameValidator is a validator for the "Patient_Name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
)
