// Code generated by entc, DO NOT EDIT.

package symptoms

const (
	// Label holds the string label denoting the symptoms type in the database.
	Label = "symptoms"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldManner holds the string denoting the manner field in the database.
	FieldManner = "manner"

	// EdgeSymptomsDiagnose holds the string denoting the symptoms_diagnose edge name in mutations.
	EdgeSymptomsDiagnose = "symptoms_diagnose"

	// Table holds the table name of the symptoms in the database.
	Table = "symptoms"
	// SymptomsDiagnoseTable is the table the holds the symptoms_diagnose relation/edge.
	SymptomsDiagnoseTable = "diagnoses"
	// SymptomsDiagnoseInverseTable is the table name for the Diagnose entity.
	// It exists in this package in order to avoid circular dependency with the "diagnose" package.
	SymptomsDiagnoseInverseTable = "diagnoses"
	// SymptomsDiagnoseColumn is the table column denoting the symptoms_diagnose relation/edge.
	SymptomsDiagnoseColumn = "symptoms_symptoms_diagnose"
)

// Columns holds all SQL columns for symptoms fields.
var Columns = []string{
	FieldID,
	FieldManner,
}

var (
	// MannerValidator is a validator for the "Manner" field. It is called by the builders before save.
	MannerValidator func(string) error
)
