// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/ADMIN/app/ent/migrate"

	"github.com/ADMIN/app/ent/diagnose"
	"github.com/ADMIN/app/ent/doctor"
	"github.com/ADMIN/app/ent/illness"
	"github.com/ADMIN/app/ent/patient"
	"github.com/ADMIN/app/ent/symptoms"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Diagnose is the client for interacting with the Diagnose builders.
	Diagnose *DiagnoseClient
	// Doctor is the client for interacting with the Doctor builders.
	Doctor *DoctorClient
	// Illness is the client for interacting with the Illness builders.
	Illness *IllnessClient
	// Patient is the client for interacting with the Patient builders.
	Patient *PatientClient
	// Symptoms is the client for interacting with the Symptoms builders.
	Symptoms *SymptomsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Diagnose = NewDiagnoseClient(c.config)
	c.Doctor = NewDoctorClient(c.config)
	c.Illness = NewIllnessClient(c.config)
	c.Patient = NewPatientClient(c.config)
	c.Symptoms = NewSymptomsClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Diagnose: NewDiagnoseClient(cfg),
		Doctor:   NewDoctorClient(cfg),
		Illness:  NewIllnessClient(cfg),
		Patient:  NewPatientClient(cfg),
		Symptoms: NewSymptomsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:   cfg,
		Diagnose: NewDiagnoseClient(cfg),
		Doctor:   NewDoctorClient(cfg),
		Illness:  NewIllnessClient(cfg),
		Patient:  NewPatientClient(cfg),
		Symptoms: NewSymptomsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Diagnose.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Diagnose.Use(hooks...)
	c.Doctor.Use(hooks...)
	c.Illness.Use(hooks...)
	c.Patient.Use(hooks...)
	c.Symptoms.Use(hooks...)
}

// DiagnoseClient is a client for the Diagnose schema.
type DiagnoseClient struct {
	config
}

// NewDiagnoseClient returns a client for the Diagnose from the given config.
func NewDiagnoseClient(c config) *DiagnoseClient {
	return &DiagnoseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `diagnose.Hooks(f(g(h())))`.
func (c *DiagnoseClient) Use(hooks ...Hook) {
	c.hooks.Diagnose = append(c.hooks.Diagnose, hooks...)
}

// Create returns a create builder for Diagnose.
func (c *DiagnoseClient) Create() *DiagnoseCreate {
	mutation := newDiagnoseMutation(c.config, OpCreate)
	return &DiagnoseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Diagnose.
func (c *DiagnoseClient) Update() *DiagnoseUpdate {
	mutation := newDiagnoseMutation(c.config, OpUpdate)
	return &DiagnoseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DiagnoseClient) UpdateOne(d *Diagnose) *DiagnoseUpdateOne {
	mutation := newDiagnoseMutation(c.config, OpUpdateOne, withDiagnose(d))
	return &DiagnoseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DiagnoseClient) UpdateOneID(id int) *DiagnoseUpdateOne {
	mutation := newDiagnoseMutation(c.config, OpUpdateOne, withDiagnoseID(id))
	return &DiagnoseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Diagnose.
func (c *DiagnoseClient) Delete() *DiagnoseDelete {
	mutation := newDiagnoseMutation(c.config, OpDelete)
	return &DiagnoseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DiagnoseClient) DeleteOne(d *Diagnose) *DiagnoseDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DiagnoseClient) DeleteOneID(id int) *DiagnoseDeleteOne {
	builder := c.Delete().Where(diagnose.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DiagnoseDeleteOne{builder}
}

// Create returns a query builder for Diagnose.
func (c *DiagnoseClient) Query() *DiagnoseQuery {
	return &DiagnoseQuery{config: c.config}
}

// Get returns a Diagnose entity by its id.
func (c *DiagnoseClient) Get(ctx context.Context, id int) (*Diagnose, error) {
	return c.Query().Where(diagnose.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DiagnoseClient) GetX(ctx context.Context, id int) *Diagnose {
	d, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return d
}

// QuerySymptoms queries the symptoms edge of a Diagnose.
func (c *DiagnoseClient) QuerySymptoms(d *Diagnose) *SymptomsQuery {
	query := &SymptomsQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(diagnose.Table, diagnose.FieldID, id),
			sqlgraph.To(symptoms.Table, symptoms.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, diagnose.SymptomsTable, diagnose.SymptomsColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryIllness queries the illness edge of a Diagnose.
func (c *DiagnoseClient) QueryIllness(d *Diagnose) *IllnessQuery {
	query := &IllnessQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(diagnose.Table, diagnose.FieldID, id),
			sqlgraph.To(illness.Table, illness.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, diagnose.IllnessTable, diagnose.IllnessColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPatient queries the patient edge of a Diagnose.
func (c *DiagnoseClient) QueryPatient(d *Diagnose) *PatientQuery {
	query := &PatientQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(diagnose.Table, diagnose.FieldID, id),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, diagnose.PatientTable, diagnose.PatientColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDoctor queries the doctor edge of a Diagnose.
func (c *DiagnoseClient) QueryDoctor(d *Diagnose) *DoctorQuery {
	query := &DoctorQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(diagnose.Table, diagnose.FieldID, id),
			sqlgraph.To(doctor.Table, doctor.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, diagnose.DoctorTable, diagnose.DoctorColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DiagnoseClient) Hooks() []Hook {
	return c.hooks.Diagnose
}

// DoctorClient is a client for the Doctor schema.
type DoctorClient struct {
	config
}

// NewDoctorClient returns a client for the Doctor from the given config.
func NewDoctorClient(c config) *DoctorClient {
	return &DoctorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `doctor.Hooks(f(g(h())))`.
func (c *DoctorClient) Use(hooks ...Hook) {
	c.hooks.Doctor = append(c.hooks.Doctor, hooks...)
}

// Create returns a create builder for Doctor.
func (c *DoctorClient) Create() *DoctorCreate {
	mutation := newDoctorMutation(c.config, OpCreate)
	return &DoctorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Doctor.
func (c *DoctorClient) Update() *DoctorUpdate {
	mutation := newDoctorMutation(c.config, OpUpdate)
	return &DoctorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DoctorClient) UpdateOne(d *Doctor) *DoctorUpdateOne {
	mutation := newDoctorMutation(c.config, OpUpdateOne, withDoctor(d))
	return &DoctorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DoctorClient) UpdateOneID(id int) *DoctorUpdateOne {
	mutation := newDoctorMutation(c.config, OpUpdateOne, withDoctorID(id))
	return &DoctorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Doctor.
func (c *DoctorClient) Delete() *DoctorDelete {
	mutation := newDoctorMutation(c.config, OpDelete)
	return &DoctorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DoctorClient) DeleteOne(d *Doctor) *DoctorDeleteOne {
	return c.DeleteOneID(d.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DoctorClient) DeleteOneID(id int) *DoctorDeleteOne {
	builder := c.Delete().Where(doctor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DoctorDeleteOne{builder}
}

// Create returns a query builder for Doctor.
func (c *DoctorClient) Query() *DoctorQuery {
	return &DoctorQuery{config: c.config}
}

// Get returns a Doctor entity by its id.
func (c *DoctorClient) Get(ctx context.Context, id int) (*Doctor, error) {
	return c.Query().Where(doctor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DoctorClient) GetX(ctx context.Context, id int) *Doctor {
	d, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return d
}

// QueryDoctorDiagnose queries the doctor_diagnose edge of a Doctor.
func (c *DoctorClient) QueryDoctorDiagnose(d *Doctor) *DiagnoseQuery {
	query := &DiagnoseQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := d.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(doctor.Table, doctor.FieldID, id),
			sqlgraph.To(diagnose.Table, diagnose.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, doctor.DoctorDiagnoseTable, doctor.DoctorDiagnoseColumn),
		)
		fromV = sqlgraph.Neighbors(d.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DoctorClient) Hooks() []Hook {
	return c.hooks.Doctor
}

// IllnessClient is a client for the Illness schema.
type IllnessClient struct {
	config
}

// NewIllnessClient returns a client for the Illness from the given config.
func NewIllnessClient(c config) *IllnessClient {
	return &IllnessClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `illness.Hooks(f(g(h())))`.
func (c *IllnessClient) Use(hooks ...Hook) {
	c.hooks.Illness = append(c.hooks.Illness, hooks...)
}

// Create returns a create builder for Illness.
func (c *IllnessClient) Create() *IllnessCreate {
	mutation := newIllnessMutation(c.config, OpCreate)
	return &IllnessCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Illness.
func (c *IllnessClient) Update() *IllnessUpdate {
	mutation := newIllnessMutation(c.config, OpUpdate)
	return &IllnessUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IllnessClient) UpdateOne(i *Illness) *IllnessUpdateOne {
	mutation := newIllnessMutation(c.config, OpUpdateOne, withIllness(i))
	return &IllnessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IllnessClient) UpdateOneID(id int) *IllnessUpdateOne {
	mutation := newIllnessMutation(c.config, OpUpdateOne, withIllnessID(id))
	return &IllnessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Illness.
func (c *IllnessClient) Delete() *IllnessDelete {
	mutation := newIllnessMutation(c.config, OpDelete)
	return &IllnessDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *IllnessClient) DeleteOne(i *Illness) *IllnessDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *IllnessClient) DeleteOneID(id int) *IllnessDeleteOne {
	builder := c.Delete().Where(illness.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IllnessDeleteOne{builder}
}

// Create returns a query builder for Illness.
func (c *IllnessClient) Query() *IllnessQuery {
	return &IllnessQuery{config: c.config}
}

// Get returns a Illness entity by its id.
func (c *IllnessClient) Get(ctx context.Context, id int) (*Illness, error) {
	return c.Query().Where(illness.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IllnessClient) GetX(ctx context.Context, id int) *Illness {
	i, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return i
}

// QueryIllnessDiagnose queries the illness_diagnose edge of a Illness.
func (c *IllnessClient) QueryIllnessDiagnose(i *Illness) *DiagnoseQuery {
	query := &DiagnoseQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := i.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(illness.Table, illness.FieldID, id),
			sqlgraph.To(diagnose.Table, diagnose.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, illness.IllnessDiagnoseTable, illness.IllnessDiagnoseColumn),
		)
		fromV = sqlgraph.Neighbors(i.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *IllnessClient) Hooks() []Hook {
	return c.hooks.Illness
}

// PatientClient is a client for the Patient schema.
type PatientClient struct {
	config
}

// NewPatientClient returns a client for the Patient from the given config.
func NewPatientClient(c config) *PatientClient {
	return &PatientClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `patient.Hooks(f(g(h())))`.
func (c *PatientClient) Use(hooks ...Hook) {
	c.hooks.Patient = append(c.hooks.Patient, hooks...)
}

// Create returns a create builder for Patient.
func (c *PatientClient) Create() *PatientCreate {
	mutation := newPatientMutation(c.config, OpCreate)
	return &PatientCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Patient.
func (c *PatientClient) Update() *PatientUpdate {
	mutation := newPatientMutation(c.config, OpUpdate)
	return &PatientUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PatientClient) UpdateOne(pa *Patient) *PatientUpdateOne {
	mutation := newPatientMutation(c.config, OpUpdateOne, withPatient(pa))
	return &PatientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PatientClient) UpdateOneID(id int) *PatientUpdateOne {
	mutation := newPatientMutation(c.config, OpUpdateOne, withPatientID(id))
	return &PatientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Patient.
func (c *PatientClient) Delete() *PatientDelete {
	mutation := newPatientMutation(c.config, OpDelete)
	return &PatientDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *PatientClient) DeleteOne(pa *Patient) *PatientDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *PatientClient) DeleteOneID(id int) *PatientDeleteOne {
	builder := c.Delete().Where(patient.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PatientDeleteOne{builder}
}

// Create returns a query builder for Patient.
func (c *PatientClient) Query() *PatientQuery {
	return &PatientQuery{config: c.config}
}

// Get returns a Patient entity by its id.
func (c *PatientClient) Get(ctx context.Context, id int) (*Patient, error) {
	return c.Query().Where(patient.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PatientClient) GetX(ctx context.Context, id int) *Patient {
	pa, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return pa
}

// QueryPatientDiagnose queries the patient_diagnose edge of a Patient.
func (c *PatientClient) QueryPatientDiagnose(pa *Patient) *DiagnoseQuery {
	query := &DiagnoseQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(patient.Table, patient.FieldID, id),
			sqlgraph.To(diagnose.Table, diagnose.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, patient.PatientDiagnoseTable, patient.PatientDiagnoseColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PatientClient) Hooks() []Hook {
	return c.hooks.Patient
}

// SymptomsClient is a client for the Symptoms schema.
type SymptomsClient struct {
	config
}

// NewSymptomsClient returns a client for the Symptoms from the given config.
func NewSymptomsClient(c config) *SymptomsClient {
	return &SymptomsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `symptoms.Hooks(f(g(h())))`.
func (c *SymptomsClient) Use(hooks ...Hook) {
	c.hooks.Symptoms = append(c.hooks.Symptoms, hooks...)
}

// Create returns a create builder for Symptoms.
func (c *SymptomsClient) Create() *SymptomsCreate {
	mutation := newSymptomsMutation(c.config, OpCreate)
	return &SymptomsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Symptoms.
func (c *SymptomsClient) Update() *SymptomsUpdate {
	mutation := newSymptomsMutation(c.config, OpUpdate)
	return &SymptomsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SymptomsClient) UpdateOne(s *Symptoms) *SymptomsUpdateOne {
	mutation := newSymptomsMutation(c.config, OpUpdateOne, withSymptoms(s))
	return &SymptomsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SymptomsClient) UpdateOneID(id int) *SymptomsUpdateOne {
	mutation := newSymptomsMutation(c.config, OpUpdateOne, withSymptomsID(id))
	return &SymptomsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Symptoms.
func (c *SymptomsClient) Delete() *SymptomsDelete {
	mutation := newSymptomsMutation(c.config, OpDelete)
	return &SymptomsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *SymptomsClient) DeleteOne(s *Symptoms) *SymptomsDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *SymptomsClient) DeleteOneID(id int) *SymptomsDeleteOne {
	builder := c.Delete().Where(symptoms.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SymptomsDeleteOne{builder}
}

// Create returns a query builder for Symptoms.
func (c *SymptomsClient) Query() *SymptomsQuery {
	return &SymptomsQuery{config: c.config}
}

// Get returns a Symptoms entity by its id.
func (c *SymptomsClient) Get(ctx context.Context, id int) (*Symptoms, error) {
	return c.Query().Where(symptoms.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SymptomsClient) GetX(ctx context.Context, id int) *Symptoms {
	s, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return s
}

// QuerySymptomsDiagnose queries the symptoms_diagnose edge of a Symptoms.
func (c *SymptomsClient) QuerySymptomsDiagnose(s *Symptoms) *DiagnoseQuery {
	query := &DiagnoseQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(symptoms.Table, symptoms.FieldID, id),
			sqlgraph.To(diagnose.Table, diagnose.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, symptoms.SymptomsDiagnoseTable, symptoms.SymptomsDiagnoseColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SymptomsClient) Hooks() []Hook {
	return c.hooks.Symptoms
}
