// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/ADMIN/app/ent/illness"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Illness is the model entity for the Illness schema.
type Illness struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// IllnessName holds the value of the "Illness_Name" field.
	IllnessName string `json:"Illness_Name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IllnessQuery when eager-loading is set.
	Edges IllnessEdges `json:"edges"`
}

// IllnessEdges holds the relations/edges for other nodes in the graph.
type IllnessEdges struct {
	// IllnessDiagnose holds the value of the illness_diagnose edge.
	IllnessDiagnose []*Diagnose
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// IllnessDiagnoseOrErr returns the IllnessDiagnose value or an error if the edge
// was not loaded in eager-loading.
func (e IllnessEdges) IllnessDiagnoseOrErr() ([]*Diagnose, error) {
	if e.loadedTypes[0] {
		return e.IllnessDiagnose, nil
	}
	return nil, &NotLoadedError{edge: "illness_diagnose"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Illness) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // Illness_Name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Illness fields.
func (i *Illness) assignValues(values ...interface{}) error {
	if m, n := len(values), len(illness.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	i.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field Illness_Name", values[0])
	} else if value.Valid {
		i.IllnessName = value.String
	}
	return nil
}

// QueryIllnessDiagnose queries the illness_diagnose edge of the Illness.
func (i *Illness) QueryIllnessDiagnose() *DiagnoseQuery {
	return (&IllnessClient{config: i.config}).QueryIllnessDiagnose(i)
}

// Update returns a builder for updating this Illness.
// Note that, you need to call Illness.Unwrap() before calling this method, if this Illness
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Illness) Update() *IllnessUpdateOne {
	return (&IllnessClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (i *Illness) Unwrap() *Illness {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Illness is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Illness) String() string {
	var builder strings.Builder
	builder.WriteString("Illness(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteString(", Illness_Name=")
	builder.WriteString(i.IllnessName)
	builder.WriteByte(')')
	return builder.String()
}

// Illnesses is a parsable slice of Illness.
type Illnesses []*Illness

func (i Illnesses) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
