// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/ADMIN/app/ent/diagnose"
	"github.com/ADMIN/app/ent/illness"
	"github.com/ADMIN/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// IllnessUpdate is the builder for updating Illness entities.
type IllnessUpdate struct {
	config
	hooks      []Hook
	mutation   *IllnessMutation
	predicates []predicate.Illness
}

// Where adds a new predicate for the builder.
func (iu *IllnessUpdate) Where(ps ...predicate.Illness) *IllnessUpdate {
	iu.predicates = append(iu.predicates, ps...)
	return iu
}

// SetIllnessName sets the Illness_Name field.
func (iu *IllnessUpdate) SetIllnessName(s string) *IllnessUpdate {
	iu.mutation.SetIllnessName(s)
	return iu
}

// AddIllnessDiagnoseIDs adds the illness_diagnose edge to Diagnose by ids.
func (iu *IllnessUpdate) AddIllnessDiagnoseIDs(ids ...int) *IllnessUpdate {
	iu.mutation.AddIllnessDiagnoseIDs(ids...)
	return iu
}

// AddIllnessDiagnose adds the illness_diagnose edges to Diagnose.
func (iu *IllnessUpdate) AddIllnessDiagnose(d ...*Diagnose) *IllnessUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return iu.AddIllnessDiagnoseIDs(ids...)
}

// Mutation returns the IllnessMutation object of the builder.
func (iu *IllnessUpdate) Mutation() *IllnessMutation {
	return iu.mutation
}

// RemoveIllnessDiagnoseIDs removes the illness_diagnose edge to Diagnose by ids.
func (iu *IllnessUpdate) RemoveIllnessDiagnoseIDs(ids ...int) *IllnessUpdate {
	iu.mutation.RemoveIllnessDiagnoseIDs(ids...)
	return iu
}

// RemoveIllnessDiagnose removes illness_diagnose edges to Diagnose.
func (iu *IllnessUpdate) RemoveIllnessDiagnose(d ...*Diagnose) *IllnessUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return iu.RemoveIllnessDiagnoseIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (iu *IllnessUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := iu.mutation.IllnessName(); ok {
		if err := illness.IllnessNameValidator(v); err != nil {
			return 0, &ValidationError{Name: "Illness_Name", err: fmt.Errorf("ent: validator failed for field \"Illness_Name\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(iu.hooks) == 0 {
		affected, err = iu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IllnessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iu.mutation = mutation
			affected, err = iu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iu.hooks) - 1; i >= 0; i-- {
			mut = iu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (iu *IllnessUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *IllnessUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *IllnessUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iu *IllnessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   illness.Table,
			Columns: illness.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: illness.FieldID,
			},
		},
	}
	if ps := iu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.IllnessName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: illness.FieldIllnessName,
		})
	}
	if nodes := iu.mutation.RemovedIllnessDiagnoseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   illness.IllnessDiagnoseTable,
			Columns: []string{illness.IllnessDiagnoseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: diagnose.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.IllnessDiagnoseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   illness.IllnessDiagnoseTable,
			Columns: []string{illness.IllnessDiagnoseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: diagnose.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{illness.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// IllnessUpdateOne is the builder for updating a single Illness entity.
type IllnessUpdateOne struct {
	config
	hooks    []Hook
	mutation *IllnessMutation
}

// SetIllnessName sets the Illness_Name field.
func (iuo *IllnessUpdateOne) SetIllnessName(s string) *IllnessUpdateOne {
	iuo.mutation.SetIllnessName(s)
	return iuo
}

// AddIllnessDiagnoseIDs adds the illness_diagnose edge to Diagnose by ids.
func (iuo *IllnessUpdateOne) AddIllnessDiagnoseIDs(ids ...int) *IllnessUpdateOne {
	iuo.mutation.AddIllnessDiagnoseIDs(ids...)
	return iuo
}

// AddIllnessDiagnose adds the illness_diagnose edges to Diagnose.
func (iuo *IllnessUpdateOne) AddIllnessDiagnose(d ...*Diagnose) *IllnessUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return iuo.AddIllnessDiagnoseIDs(ids...)
}

// Mutation returns the IllnessMutation object of the builder.
func (iuo *IllnessUpdateOne) Mutation() *IllnessMutation {
	return iuo.mutation
}

// RemoveIllnessDiagnoseIDs removes the illness_diagnose edge to Diagnose by ids.
func (iuo *IllnessUpdateOne) RemoveIllnessDiagnoseIDs(ids ...int) *IllnessUpdateOne {
	iuo.mutation.RemoveIllnessDiagnoseIDs(ids...)
	return iuo
}

// RemoveIllnessDiagnose removes illness_diagnose edges to Diagnose.
func (iuo *IllnessUpdateOne) RemoveIllnessDiagnose(d ...*Diagnose) *IllnessUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return iuo.RemoveIllnessDiagnoseIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (iuo *IllnessUpdateOne) Save(ctx context.Context) (*Illness, error) {
	if v, ok := iuo.mutation.IllnessName(); ok {
		if err := illness.IllnessNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Illness_Name", err: fmt.Errorf("ent: validator failed for field \"Illness_Name\": %w", err)}
		}
	}

	var (
		err  error
		node *Illness
	)
	if len(iuo.hooks) == 0 {
		node, err = iuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*IllnessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iuo.mutation = mutation
			node, err = iuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(iuo.hooks) - 1; i >= 0; i-- {
			mut = iuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *IllnessUpdateOne) SaveX(ctx context.Context) *Illness {
	i, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return i
}

// Exec executes the query on the entity.
func (iuo *IllnessUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *IllnessUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (iuo *IllnessUpdateOne) sqlSave(ctx context.Context) (i *Illness, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   illness.Table,
			Columns: illness.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: illness.FieldID,
			},
		},
	}
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Illness.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := iuo.mutation.IllnessName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: illness.FieldIllnessName,
		})
	}
	if nodes := iuo.mutation.RemovedIllnessDiagnoseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   illness.IllnessDiagnoseTable,
			Columns: []string{illness.IllnessDiagnoseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: diagnose.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.IllnessDiagnoseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   illness.IllnessDiagnoseTable,
			Columns: []string{illness.IllnessDiagnoseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: diagnose.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	i = &Illness{config: iuo.config}
	_spec.Assign = i.assignValues
	_spec.ScanValues = i.scanValues()
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{illness.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return i, nil
}
