// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/ADMIN/app/ent/doctor"
	"github.com/ADMIN/app/ent/illness"
	"github.com/ADMIN/app/ent/patient"
	"github.com/ADMIN/app/ent/schema"
	"github.com/ADMIN/app/ent/symptoms"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	doctorFields := schema.Doctor{}.Fields()
	_ = doctorFields
	// doctorDescDoctorNAME is the schema descriptor for Doctor_NAME field.
	doctorDescDoctorNAME := doctorFields[0].Descriptor()
	// doctor.DoctorNAMEValidator is a validator for the "Doctor_NAME" field. It is called by the builders before save.
	doctor.DoctorNAMEValidator = doctorDescDoctorNAME.Validators[0].(func(string) error)
	// doctorDescDoctorEmail is the schema descriptor for Doctor_Email field.
	doctorDescDoctorEmail := doctorFields[1].Descriptor()
	// doctor.DoctorEmailValidator is a validator for the "Doctor_Email" field. It is called by the builders before save.
	doctor.DoctorEmailValidator = doctorDescDoctorEmail.Validators[0].(func(string) error)
	illnessFields := schema.Illness{}.Fields()
	_ = illnessFields
	// illnessDescIllnessName is the schema descriptor for Illness_Name field.
	illnessDescIllnessName := illnessFields[0].Descriptor()
	// illness.IllnessNameValidator is a validator for the "Illness_Name" field. It is called by the builders before save.
	illness.IllnessNameValidator = illnessDescIllnessName.Validators[0].(func(string) error)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescPatientName is the schema descriptor for Patient_Name field.
	patientDescPatientName := patientFields[0].Descriptor()
	// patient.PatientNameValidator is a validator for the "Patient_Name" field. It is called by the builders before save.
	patient.PatientNameValidator = patientDescPatientName.Validators[0].(func(string) error)
	symptomsFields := schema.Symptoms{}.Fields()
	_ = symptomsFields
	// symptomsDescManner is the schema descriptor for Manner field.
	symptomsDescManner := symptomsFields[0].Descriptor()
	// symptoms.MannerValidator is a validator for the "Manner" field. It is called by the builders before save.
	symptoms.MannerValidator = symptomsDescManner.Validators[0].(func(string) error)
}
