// Code generated by entc, DO NOT EDIT.

package doctor

const (
	// Label holds the string label denoting the doctor type in the database.
	Label = "doctor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDoctorNAME holds the string denoting the doctor_name field in the database.
	FieldDoctorNAME = "doctor_name"
	// FieldDoctorEmail holds the string denoting the doctor_email field in the database.
	FieldDoctorEmail = "doctor_email"

	// EdgeDoctorDiagnose holds the string denoting the doctor_diagnose edge name in mutations.
	EdgeDoctorDiagnose = "doctor_diagnose"

	// Table holds the table name of the doctor in the database.
	Table = "doctors"
	// DoctorDiagnoseTable is the table the holds the doctor_diagnose relation/edge.
	DoctorDiagnoseTable = "diagnoses"
	// DoctorDiagnoseInverseTable is the table name for the Diagnose entity.
	// It exists in this package in order to avoid circular dependency with the "diagnose" package.
	DoctorDiagnoseInverseTable = "diagnoses"
	// DoctorDiagnoseColumn is the table column denoting the doctor_diagnose relation/edge.
	DoctorDiagnoseColumn = "doctor_doctor_diagnose"
)

// Columns holds all SQL columns for doctor fields.
var Columns = []string{
	FieldID,
	FieldDoctorNAME,
	FieldDoctorEmail,
}

var (
	// DoctorNAMEValidator is a validator for the "Doctor_NAME" field. It is called by the builders before save.
	DoctorNAMEValidator func(string) error
	// DoctorEmailValidator is a validator for the "Doctor_Email" field. It is called by the builders before save.
	DoctorEmailValidator func(string) error
)
