// Code generated by entc, DO NOT EDIT.

package doctor

import (
	"github.com/ADMIN/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// DoctorNAME applies equality check predicate on the "Doctor_NAME" field. It's identical to DoctorNAMEEQ.
func DoctorNAME(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDoctorNAME), v))
	})
}

// DoctorEmail applies equality check predicate on the "Doctor_Email" field. It's identical to DoctorEmailEQ.
func DoctorEmail(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDoctorEmail), v))
	})
}

// DoctorNAMEEQ applies the EQ predicate on the "Doctor_NAME" field.
func DoctorNAMEEQ(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMENEQ applies the NEQ predicate on the "Doctor_NAME" field.
func DoctorNAMENEQ(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEIn applies the In predicate on the "Doctor_NAME" field.
func DoctorNAMEIn(vs ...string) predicate.Doctor {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Doctor(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDoctorNAME), v...))
	})
}

// DoctorNAMENotIn applies the NotIn predicate on the "Doctor_NAME" field.
func DoctorNAMENotIn(vs ...string) predicate.Doctor {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Doctor(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDoctorNAME), v...))
	})
}

// DoctorNAMEGT applies the GT predicate on the "Doctor_NAME" field.
func DoctorNAMEGT(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEGTE applies the GTE predicate on the "Doctor_NAME" field.
func DoctorNAMEGTE(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMELT applies the LT predicate on the "Doctor_NAME" field.
func DoctorNAMELT(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMELTE applies the LTE predicate on the "Doctor_NAME" field.
func DoctorNAMELTE(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEContains applies the Contains predicate on the "Doctor_NAME" field.
func DoctorNAMEContains(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEHasPrefix applies the HasPrefix predicate on the "Doctor_NAME" field.
func DoctorNAMEHasPrefix(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEHasSuffix applies the HasSuffix predicate on the "Doctor_NAME" field.
func DoctorNAMEHasSuffix(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEEqualFold applies the EqualFold predicate on the "Doctor_NAME" field.
func DoctorNAMEEqualFold(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDoctorNAME), v))
	})
}

// DoctorNAMEContainsFold applies the ContainsFold predicate on the "Doctor_NAME" field.
func DoctorNAMEContainsFold(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDoctorNAME), v))
	})
}

// DoctorEmailEQ applies the EQ predicate on the "Doctor_Email" field.
func DoctorEmailEQ(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailNEQ applies the NEQ predicate on the "Doctor_Email" field.
func DoctorEmailNEQ(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailIn applies the In predicate on the "Doctor_Email" field.
func DoctorEmailIn(vs ...string) predicate.Doctor {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Doctor(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDoctorEmail), v...))
	})
}

// DoctorEmailNotIn applies the NotIn predicate on the "Doctor_Email" field.
func DoctorEmailNotIn(vs ...string) predicate.Doctor {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Doctor(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDoctorEmail), v...))
	})
}

// DoctorEmailGT applies the GT predicate on the "Doctor_Email" field.
func DoctorEmailGT(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailGTE applies the GTE predicate on the "Doctor_Email" field.
func DoctorEmailGTE(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailLT applies the LT predicate on the "Doctor_Email" field.
func DoctorEmailLT(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailLTE applies the LTE predicate on the "Doctor_Email" field.
func DoctorEmailLTE(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailContains applies the Contains predicate on the "Doctor_Email" field.
func DoctorEmailContains(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailHasPrefix applies the HasPrefix predicate on the "Doctor_Email" field.
func DoctorEmailHasPrefix(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailHasSuffix applies the HasSuffix predicate on the "Doctor_Email" field.
func DoctorEmailHasSuffix(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailEqualFold applies the EqualFold predicate on the "Doctor_Email" field.
func DoctorEmailEqualFold(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldDoctorEmail), v))
	})
}

// DoctorEmailContainsFold applies the ContainsFold predicate on the "Doctor_Email" field.
func DoctorEmailContainsFold(v string) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldDoctorEmail), v))
	})
}

// HasDoctorDiagnose applies the HasEdge predicate on the "doctor_diagnose" edge.
func HasDoctorDiagnose() predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoctorDiagnoseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DoctorDiagnoseTable, DoctorDiagnoseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoctorDiagnoseWith applies the HasEdge predicate on the "doctor_diagnose" edge with a given conditions (other predicates).
func HasDoctorDiagnoseWith(preds ...predicate.Diagnose) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoctorDiagnoseInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DoctorDiagnoseTable, DoctorDiagnoseColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Doctor) predicate.Doctor {
	return predicate.Doctor(func(s *sql.Selector) {
		p(s.Not())
	})
}
