// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// DiagnosesColumns holds the columns for the "diagnoses" table.
	DiagnosesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "doctor_doctor_diagnose", Type: field.TypeInt, Nullable: true},
		{Name: "illness_illness_diagnose", Type: field.TypeInt, Nullable: true},
		{Name: "patient_patient_diagnose", Type: field.TypeInt, Nullable: true},
		{Name: "symptoms_symptoms_diagnose", Type: field.TypeInt, Nullable: true},
	}
	// DiagnosesTable holds the schema information for the "diagnoses" table.
	DiagnosesTable = &schema.Table{
		Name:       "diagnoses",
		Columns:    DiagnosesColumns,
		PrimaryKey: []*schema.Column{DiagnosesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:  "diagnoses_doctors_doctor_diagnose",
				Columns: []*schema.Column{DiagnosesColumns[1]},

				RefColumns: []*schema.Column{DoctorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "diagnoses_illnesses_illness_diagnose",
				Columns: []*schema.Column{DiagnosesColumns[2]},

				RefColumns: []*schema.Column{IllnessesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "diagnoses_patients_patient_diagnose",
				Columns: []*schema.Column{DiagnosesColumns[3]},

				RefColumns: []*schema.Column{PatientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:  "diagnoses_symptoms_symptoms_diagnose",
				Columns: []*schema.Column{DiagnosesColumns[4]},

				RefColumns: []*schema.Column{SymptomsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// DoctorsColumns holds the columns for the "doctors" table.
	DoctorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "doctor_name", Type: field.TypeString},
		{Name: "doctor_email", Type: field.TypeString},
	}
	// DoctorsTable holds the schema information for the "doctors" table.
	DoctorsTable = &schema.Table{
		Name:        "doctors",
		Columns:     DoctorsColumns,
		PrimaryKey:  []*schema.Column{DoctorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// IllnessesColumns holds the columns for the "illnesses" table.
	IllnessesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "illness_name", Type: field.TypeString},
	}
	// IllnessesTable holds the schema information for the "illnesses" table.
	IllnessesTable = &schema.Table{
		Name:        "illnesses",
		Columns:     IllnessesColumns,
		PrimaryKey:  []*schema.Column{IllnessesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// PatientsColumns holds the columns for the "patients" table.
	PatientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "patient_name", Type: field.TypeString},
	}
	// PatientsTable holds the schema information for the "patients" table.
	PatientsTable = &schema.Table{
		Name:        "patients",
		Columns:     PatientsColumns,
		PrimaryKey:  []*schema.Column{PatientsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// SymptomsColumns holds the columns for the "symptoms" table.
	SymptomsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "manner", Type: field.TypeString},
	}
	// SymptomsTable holds the schema information for the "symptoms" table.
	SymptomsTable = &schema.Table{
		Name:        "symptoms",
		Columns:     SymptomsColumns,
		PrimaryKey:  []*schema.Column{SymptomsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DiagnosesTable,
		DoctorsTable,
		IllnessesTable,
		PatientsTable,
		SymptomsTable,
	}
)

func init() {
	DiagnosesTable.ForeignKeys[0].RefTable = DoctorsTable
	DiagnosesTable.ForeignKeys[1].RefTable = IllnessesTable
	DiagnosesTable.ForeignKeys[2].RefTable = PatientsTable
	DiagnosesTable.ForeignKeys[3].RefTable = SymptomsTable
}
