/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersDiagnose
 */
export interface ControllersDiagnose {
    /**
     * 
     * @type {number}
     * @memberof ControllersDiagnose
     */
    doctor?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDiagnose
     */
    illness?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDiagnose
     */
    patient?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDiagnose
     */
    symptoms?: number;
}

export function ControllersDiagnoseFromJSON(json: any): ControllersDiagnose {
    return ControllersDiagnoseFromJSONTyped(json, false);
}

export function ControllersDiagnoseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersDiagnose {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctor': !exists(json, 'doctor') ? undefined : json['doctor'],
        'illness': !exists(json, 'illness') ? undefined : json['illness'],
        'patient': !exists(json, 'patient') ? undefined : json['patient'],
        'symptoms': !exists(json, 'symptoms') ? undefined : json['symptoms'],
    };
}

export function ControllersDiagnoseToJSON(value?: ControllersDiagnose | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor': value.doctor,
        'illness': value.illness,
        'patient': value.patient,
        'symptoms': value.symptoms,
    };
}


