/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctor,
    EntDoctorFromJSON,
    EntDoctorFromJSONTyped,
    EntDoctorToJSON,
    EntIllness,
    EntIllnessFromJSON,
    EntIllnessFromJSONTyped,
    EntIllnessToJSON,
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntSymptoms,
    EntSymptomsFromJSON,
    EntSymptomsFromJSONTyped,
    EntSymptomsToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDiagnoseEdges
 */
export interface EntDiagnoseEdges {
    /**
     * 
     * @type {EntDoctor}
     * @memberof EntDiagnoseEdges
     */
    doctor?: EntDoctor;
    /**
     * 
     * @type {EntIllness}
     * @memberof EntDiagnoseEdges
     */
    illness?: EntIllness;
    /**
     * 
     * @type {EntPatient}
     * @memberof EntDiagnoseEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntSymptoms}
     * @memberof EntDiagnoseEdges
     */
    symptoms?: EntSymptoms;
}

export function EntDiagnoseEdgesFromJSON(json: any): EntDiagnoseEdges {
    return EntDiagnoseEdgesFromJSONTyped(json, false);
}

export function EntDiagnoseEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDiagnoseEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doctor': !exists(json, 'Doctor') ? undefined : EntDoctorFromJSON(json['Doctor']),
        'illness': !exists(json, 'Illness') ? undefined : EntIllnessFromJSON(json['Illness']),
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
        'symptoms': !exists(json, 'Symptoms') ? undefined : EntSymptomsFromJSON(json['Symptoms']),
    };
}

export function EntDiagnoseEdgesToJSON(value?: EntDiagnoseEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doctor': EntDoctorToJSON(value.doctor),
        'illness': EntIllnessToJSON(value.illness),
        'patient': EntPatientToJSON(value.patient),
        'symptoms': EntSymptomsToJSON(value.symptoms),
    };
}


