/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntIllnessEdges,
    EntIllnessEdgesFromJSON,
    EntIllnessEdgesFromJSONTyped,
    EntIllnessEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntIllness
 */
export interface EntIllness {
    /**
     * IllnessName holds the value of the "Illness_Name" field.
     * @type {string}
     * @memberof EntIllness
     */
    illnessName?: string;
    /**
     * 
     * @type {EntIllnessEdges}
     * @memberof EntIllness
     */
    edges?: EntIllnessEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntIllness
     */
    id?: number;
}

export function EntIllnessFromJSON(json: any): EntIllness {
    return EntIllnessFromJSONTyped(json, false);
}

export function EntIllnessFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntIllness {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'illnessName': !exists(json, 'Illness_Name') ? undefined : json['Illness_Name'],
        'edges': !exists(json, 'edges') ? undefined : EntIllnessEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntIllnessToJSON(value?: EntIllness | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Illness_Name': value.illnessName,
        'edges': EntIllnessEdgesToJSON(value.edges),
        'id': value.id,
    };
}


