/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDiagnose,
    EntDiagnoseFromJSON,
    EntDiagnoseFromJSONTyped,
    EntDiagnoseToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntPatientEdges
 */
export interface EntPatientEdges {
    /**
     * PatientDiagnose holds the value of the patient_diagnose edge.
     * @type {Array<EntDiagnose>}
     * @memberof EntPatientEdges
     */
    patientDiagnose?: Array<EntDiagnose>;
}

export function EntPatientEdgesFromJSON(json: any): EntPatientEdges {
    return EntPatientEdgesFromJSONTyped(json, false);
}

export function EntPatientEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntPatientEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patientDiagnose': !exists(json, 'patientDiagnose') ? undefined : ((json['patientDiagnose'] as Array<any>).map(EntDiagnoseFromJSON)),
    };
}

export function EntPatientEdgesToJSON(value?: EntPatientEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patientDiagnose': value.patientDiagnose === undefined ? undefined : ((value.patientDiagnose as Array<any>).map(EntDiagnoseToJSON)),
    };
}


