/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Playlist Vidoe
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDiagnose,
    EntDiagnoseFromJSON,
    EntDiagnoseFromJSONTyped,
    EntDiagnoseToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSymptomsEdges
 */
export interface EntSymptomsEdges {
    /**
     * SymptomsDiagnose holds the value of the symptoms_diagnose edge.
     * @type {Array<EntDiagnose>}
     * @memberof EntSymptomsEdges
     */
    symptomsDiagnose?: Array<EntDiagnose>;
}

export function EntSymptomsEdgesFromJSON(json: any): EntSymptomsEdges {
    return EntSymptomsEdgesFromJSONTyped(json, false);
}

export function EntSymptomsEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSymptomsEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'symptomsDiagnose': !exists(json, 'symptomsDiagnose') ? undefined : ((json['symptomsDiagnose'] as Array<any>).map(EntDiagnoseFromJSON)),
    };
}

export function EntSymptomsEdgesToJSON(value?: EntSymptomsEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'symptomsDiagnose': value.symptomsDiagnose === undefined ? undefined : ((value.symptomsDiagnose as Array<any>).map(EntDiagnoseToJSON)),
    };
}


